# Generated by Django 5.2 on 2025-06-10 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book_category',
        ),
        migrations.AddField(
            model_name='books',
            name='img_url',
            field=models.TextField(default='book_url', max_length=150),
        ),
    ]
