# Generated by Django 5.2 on 2025-06-10 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_delete_book_category_books_img_url'),
        ('renter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='renter.book_category'),
        ),
    ]
