# Generated by Django 5.2 on 2025-06-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_rental_delete_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
