# Generated by Django 5.2 on 2025-06-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0003_rental_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
