# Generated by Django 5.2 on 2025-06-16 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0004_alter_rental_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_returned',
        ),
    ]
