# Generated by Django 5.2 on 2025-06-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0007_rental_is_returned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='is_returned',
        ),
        migrations.AddField(
            model_name='rental',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
