# Generated by Django 5.2 on 2025-06-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0008_remove_rental_is_returned_rental_return_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
    ]
