# Generated by Django 5.2 on 2025-06-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0009_rental_is_returned'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='fine_to_pay',
            field=models.FloatField(default=0),
        ),
    ]
